import type { ConstructorWorkspace } from "./constructor-hub.types";

export function getMockConstructorWorkspace(flowId: string, role: ConstructorWorkspace["currentUserRole"]): ConstructorWorkspace {
  const now = new Date();
  const iso = (d: Date) => d.toISOString();
  const addHours = (h: number) => new Date(now.getTime() + h * 60 * 60 * 1000);
  const addDays = (d: number) => new Date(now.getTime() + d * 24 * 60 * 60 * 1000);

  return {
    header: {
      flowId,
      dealId: `deal-${flowId}`,
      dealNumber: "ORD-2026-0415",
      projectName: "Кухня + гардероб в ЖК RiverStone",
      clientName: "Анна Коваль",
      objectAddress: "Киев, Днепровская наб., 14",
      managerName: "Марина Полещук",
      headOfProductionName: "Олег Середа",
      assignedConstructorName: "Александр Мельник",
      deadlineAt: iso(addDays(2)),
      priority: "HIGH",
      status: "HAS_QUESTIONS",
    },
    stages: [
      { id: "1", label: "Назначение", state: "DONE" },
      { id: "2", label: "Изучение ТЗ", state: "DONE" },
      { id: "3", label: "Конструирование", state: "ACTIVE" },
      { id: "4", label: "Проверка", state: "PENDING" },
      { id: "5", label: "Передача в цех", state: "PENDING" },
    ],
    tasks: [
      { id: "t1", title: "Свести размеры по нишам кухни", done: true, dueAt: iso(addHours(-20)) },
      { id: "t2", title: "Проверить фасады на коллизию с вытяжкой", done: false, dueAt: iso(addHours(8)) },
      { id: "t3", title: "Подготовить финальную спецификацию фурнитуры", done: false, dueAt: iso(addDays(1)) },
    ],
    checklist: [
      { id: "c1", label: "Изучить ТЗ", done: true, required: true },
      { id: "c2", label: "Проверить замеры", done: true, required: true },
      { id: "c3", label: "Проверить согласованные материалы", done: true, required: true },
      { id: "c4", label: "Уточнить открытые вопросы", done: false, required: true },
      { id: "c5", label: "Загрузить черновик", done: false, required: true },
      { id: "c6", label: "Отправить на проверку", done: false, required: true },
    ],
    zoneProgress: [
      { id: "z1", zoneName: "Кухня", progressPercent: 100 },
      { id: "z2", zoneName: "Шкаф", progressPercent: 60 },
      { id: "z3", zoneName: "Гардероб", progressPercent: 20 },
    ],
    techSections: [
      {
        id: "s1",
        title: "Общая информация",
        summary: "Согласованы конфигурация и стилистика проекта.",
        completionPercent: 100,
        updatedAt: iso(addDays(-3)),
        details: ["Стиль: современный минимализм", "Финиш: матовый", "Срок запуска: 2 недели после апрува"],
      },
      {
        id: "s2",
        title: "Помещения / зоны",
        summary: "3 зоны с разной готовностью к выпуску чертежей.",
        completionPercent: 74,
        updatedAt: iso(addDays(-1)),
        details: ["Кухня: готово", "Шкаф: в работе", "Гардероб: уточнение наполнения"],
      },
      {
        id: "s3",
        title: "Модули / изделия",
        summary: "Модули под технику готовы, остались доборы.",
        completionPercent: 80,
        updatedAt: iso(addHours(-20)),
        details: ["Под встраиваемую технику закладные учтены", "Нужна финальная привязка по доборам"],
      },
      {
        id: "s4",
        title: "Материалы",
        summary: "Часть материалов согласована, нет итоговой карты кромок.",
        completionPercent: 70,
        updatedAt: iso(addHours(-18)),
        details: ["Корпус: Egger W1000 ST9", "Кромка: ABS 1 мм", "Нет итоговой схемы кромления"],
      },
      {
        id: "s5",
        title: "Фасады",
        summary: "Фасады согласованы, требуется проверка зазоров.",
        completionPercent: 85,
        updatedAt: iso(addHours(-10)),
        details: ["МДФ фарба RAL 9016", "Ручка профиль Gola", "Нужна проверка по угловой секции"],
      },
      {
        id: "s6",
        title: "Фурнитура",
        summary: "Есть расхождение по петлям на пенале.",
        completionPercent: 62,
        updatedAt: iso(addHours(-6)),
        details: ["Blum Tandembox", "Петли: часть без доводчика в старом списке"],
      },
      {
        id: "s7",
        title: "Подсветка / техника",
        summary: "Нет схемы подключения подсветки.",
        completionPercent: 40,
        updatedAt: iso(addHours(-4)),
        details: ["Лента 24V согласована", "Отсутствует схема драйверов/каналов"],
      },
      {
        id: "s8",
        title: "Монтажные особенности",
        summary: "Риск по кривизне стены в зоне колонн.",
        completionPercent: 55,
        updatedAt: iso(addHours(-5)),
        details: ["Отклонение стены до 18 мм", "Нужны компенсационные планки"],
      },
      {
        id: "s9",
        title: "Риски",
        summary: "Выявлено 3 операционных риска.",
        completionPercent: 66,
        updatedAt: iso(addHours(-3)),
        details: ["Ниша под холодильник: расхождение размеров", "Не загружен итоговый список фурнитуры", "Нет финального фото скрытых коммуникаций"],
      },
      {
        id: "s10",
        title: "Что обязательно учесть",
        summary: "Критичные ограничения перед отправкой в цех.",
        completionPercent: 78,
        updatedAt: iso(addHours(-2)),
        details: ["Сохранять вентзазор 30 мм", "Проверить диагонали на месте монтажа", "Нельзя запускать без закрытия CRITICAL-вопросов"],
      },
    ],
    questions: [
      {
        id: "q1",
        text: "Подтвердите финальную ширину ниши под холодильник: 2580 или 2600 мм?",
        category: "SIZES",
        addressedTo: "MEASURER",
        priority: "CRITICAL",
        status: "OPEN",
        authorName: "Александр Мельник",
        createdAt: iso(addHours(-12)),
        pinned: true,
        answerPreview: null,
      },
      {
        id: "q2",
        text: "Какую модель направляющих утверждаем для верхних ящиков?",
        category: "MATERIALS",
        addressedTo: "MANAGER",
        priority: "HIGH",
        status: "IN_PROGRESS",
        authorName: "Александр Мельник",
        createdAt: iso(addHours(-18)),
        pinned: false,
        answerPreview: "Ожидаем финальный ответ от поставщика до 18:00.",
      },
      {
        id: "q3",
        text: "Есть ли подтверждение по расположению розеток для подсветки?",
        category: "TECH",
        addressedTo: "HEAD_OF_PRODUCTION",
        priority: "MEDIUM",
        status: "CLOSED",
        authorName: "Марина Полещук",
        createdAt: iso(addDays(-2)),
        pinned: false,
        answerPreview: "Да, согласовано в чате, схема добавлена в пакет v3.",
      },
    ],
    files: [
      {
        id: "f1",
        fileName: "Kitchen_plan_v3.pdf",
        category: "PROPOSAL_APPROVED",
        uploadedBy: "Марина Полещук",
        uploadedAt: iso(addDays(-3)),
        versionLabel: "v3",
        extension: "pdf",
        previewUrl: null,
        downloadUrl: null,
        approved: true,
        important: true,
        archived: false,
        mine: false,
        comments: [{ id: "c1", authorName: "Александр Мельник", text: "Использую как базовую версию.", createdAt: iso(addDays(-2)) }],
      },
      {
        id: "f2",
        fileName: "Measurements_2026_04_05.xlsx",
        category: "MEASUREMENTS",
        uploadedBy: "Игорь Ярема",
        uploadedAt: iso(addDays(-2)),
        versionLabel: "v2",
        extension: "xlsx",
        previewUrl: null,
        downloadUrl: null,
        approved: true,
        important: true,
        archived: false,
        mine: false,
        comments: [],
      },
      {
        id: "f3",
        fileName: "Draft_drawings_revA.dwg",
        category: "OLD_VERSIONS",
        uploadedBy: "Александр Мельник",
        uploadedAt: iso(addHours(-16)),
        versionLabel: "revA",
        extension: "dwg",
        previewUrl: null,
        downloadUrl: null,
        approved: false,
        important: false,
        archived: true,
        mine: true,
        comments: [{ id: "c2", authorName: "Олег Середа", text: "Вернуть с уточнением фурнитуры.", createdAt: iso(addHours(-8)) }],
      },
      {
        id: "f4",
        fileName: "Final_specification_v4.xlsx",
        category: "FINAL_FOR_PRODUCTION",
        uploadedBy: "Александр Мельник",
        uploadedAt: iso(addHours(-1)),
        versionLabel: "v4",
        extension: "xlsx",
        previewUrl: null,
        downloadUrl: null,
        approved: false,
        important: true,
        archived: false,
        mine: true,
        comments: [],
      },
    ],
    versions: [
      {
        id: "v1",
        versionLabel: "v2",
        type: "DRAFT",
        uploadedAt: iso(addDays(-2)),
        uploadedBy: "Александр Мельник",
        changeSummary: "Базовая компоновка по кухням и модульным шкафам.",
        approvalStatus: "RETURNED",
      },
      {
        id: "v2",
        versionLabel: "v3",
        type: "REVIEW",
        uploadedAt: iso(addHours(-20)),
        uploadedBy: "Александр Мельник",
        changeSummary: "Доработаны размеры, добавлены узлы крепления.",
        approvalStatus: "PENDING",
      },
      {
        id: "v3",
        versionLabel: "v4",
        type: "FINAL",
        uploadedAt: iso(addHours(-1)),
        uploadedBy: "Александр Мельник",
        changeSummary: "Финальная спецификация и карта фурнитуры.",
        approvalStatus: "PENDING",
      },
    ],
    approvalReviews: [
      {
        id: "r1",
        createdAt: iso(addDays(-1)),
        reviewerName: "Олег Середа",
        decision: "RETURNED",
        severity: "MAJOR",
        reason: "Не подтверждены размеры ниши, нет финальной карты фурнитуры.",
        remarks: ["Уточнить габарит под холодильник", "Добавить список петель по секциям"],
      },
    ],
    timeline: [
      {
        id: "h1",
        type: "ASSIGNED",
        title: "Назначен конструктор",
        description: "Проект передан в рабочую зону конструктора.",
        actorName: "Олег Середа",
        createdAt: iso(addDays(-4)),
      },
      {
        id: "h2",
        type: "MEASUREMENTS_UPLOADED",
        title: "Загружены замеры",
        description: "Добавлен пакет актуальных замеров v2.",
        actorName: "Игорь Ярема",
        createdAt: iso(addDays(-2)),
      },
      {
        id: "h3",
        type: "QUESTION_CREATED",
        title: "Создан вопрос по размерам",
        description: "Запрос по уточнению ниши для техники.",
        actorName: "Александр Мельник",
        createdAt: iso(addHours(-12)),
      },
      {
        id: "h4",
        type: "DRAFT_UPLOADED",
        title: "Загружен черновик",
        description: "Пакет чертежей revA отправлен на проверку.",
        actorName: "Александр Мельник",
        createdAt: iso(addHours(-10)),
      },
    ],
    aiAlerts: [
      {
        id: "a1",
        level: "CRITICAL",
        section: "RISKS",
        message: "Несоответствие замера: ниша 2600 мм вместо 2580 мм.",
      },
      {
        id: "a2",
        level: "WARNING",
        section: "MISSING",
        message: "Нет схемы подключения подсветки.",
      },
      {
        id: "a3",
        level: "WARNING",
        section: "MISSING",
        message: "Не загружен полный список фурнитуры.",
      },
      {
        id: "a4",
        level: "INFO",
        section: "CHECK",
        message: "Есть 2 неотвеченных вопроса по монтажу и размерам.",
      },
    ],
    approvedSummary: {
      lines: [
        { id: "as1", label: "Цена", state: "APPROVED", summary: "1 248 000 грн (КП v3)" },
        { id: "as2", label: "Версия КП", state: "APPROVED", summary: "v3 от 05.04.2026" },
        { id: "as3", label: "Размеры", state: "OUTDATED", summary: "Есть конфликт по нише техники" },
        { id: "as4", label: "Материалы", state: "APPROVED", summary: "Egger W1000 ST9, кромка ABS 1мм" },
        { id: "as5", label: "Фурнитура", state: "MISSING", summary: "Нужен финальный подтвержденный список" },
        { id: "as6", label: "Техника", state: "APPROVED", summary: "Согласованы позиции в спецификации клиента" },
        { id: "as7", label: "Контрольный замер", state: "APPROVED", summary: "Выполнен 05.04.2026" },
        { id: "as8", label: "Последние изменения", state: "APPROVED", summary: "Перенос пенала + доборы в углу" },
      ],
    },
    contacts: [
      { id: "p1", roleLabel: "Менеджер", name: "Марина Полещук", phone: "+380671112233" },
      { id: "p2", roleLabel: "Замерщик", name: "Игорь Ярема", phone: "+380671144556" },
      { id: "p3", roleLabel: "Нач. производства", name: "Олег Середа", phone: "+380671198877" },
      { id: "p4", roleLabel: "Конструктор", name: "Александр Мельник", phone: "+380671231122" },
      { id: "p5", roleLabel: "Клиент", name: "Анна Коваль", phone: null },
    ],
    communication: [
      {
        id: "m1",
        authorName: "Марина Полещук",
        authorRole: "Менеджер",
        text: "Пожалуйста, приоритетно закрой вопрос по нише под холодильник.",
        createdAt: iso(addHours(-7)),
      },
      {
        id: "m2",
        authorName: "Александр Мельник",
        authorRole: "Конструктор",
        text: "Принял. После ответа по замерам отправлю на проверку.",
        createdAt: iso(addHours(-6)),
      },
    ],
    currentUserRole: role,
  };
}
