import type { ProductionCommandCenterView, ProductionOrderHubView } from "../../types/production";

export const DEMO_FLOW_ID = "demo-flow-1";
const DEMO_FLOW_IDS = [
  "demo-flow-1",
  "demo-flow-2",
  "demo-flow-3",
  "demo-flow-4",
  "demo-flow-5",
  "demo-flow-6",
] as const;

const now = Date.now();

const DEMO_QUEUE: ProductionCommandCenterView["queue"] = [
  {
    id: "demo-flow-1",
    number: "PR-101",
    clientName: "ТОВ Альфа Інтер'єр",
    title: "Кухня модульна",
    currentStepKey: "ACCEPTED_BY_CHIEF",
    status: "NEW",
    readinessPercent: 10,
    riskScore: 18,
    dueDate: new Date(now + 10 * 24 * 60 * 60 * 1000).toISOString(),
    blockersCount: 0,
    openQuestionsCount: 0,
  },
  {
    id: "demo-flow-2",
    number: "PR-102",
    clientName: "ФОП Іваненко",
    title: "Шафа-купе",
    currentStepKey: "CONSTRUCTOR_ASSIGNED",
    status: "ACTIVE",
    readinessPercent: 24,
    riskScore: 35,
    dueDate: new Date(now + 7 * 24 * 60 * 60 * 1000).toISOString(),
    blockersCount: 0,
    openQuestionsCount: 1,
  },
  {
    id: "demo-flow-3",
    number: "PR-103",
    clientName: "ТОВ Нова Оселя",
    title: "Гардеробна система",
    currentStepKey: "CONSTRUCTOR_IN_PROGRESS",
    status: "ACTIVE",
    readinessPercent: 42,
    riskScore: 49,
    dueDate: new Date(now + 5 * 24 * 60 * 60 * 1000).toISOString(),
    blockersCount: 1,
    openQuestionsCount: 2,
  },
  {
    id: "demo-flow-4",
    number: "PR-104",
    clientName: "ТОВ Silver Home",
    title: "Столи офісні",
    currentStepKey: "FILES_VALIDATED",
    status: "BLOCKED",
    readinessPercent: 61,
    riskScore: 77,
    dueDate: new Date(now - 1 * 24 * 60 * 60 * 1000).toISOString(),
    blockersCount: 2,
    openQuestionsCount: 1,
  },
  {
    id: "demo-flow-5",
    number: "PR-105",
    clientName: "ФОП Марчук",
    title: "Тумби ванні",
    currentStepKey: "APPROVED_BY_CHIEF",
    status: "ACTIVE",
    readinessPercent: 86,
    riskScore: 28,
    dueDate: new Date(now + 3 * 24 * 60 * 60 * 1000).toISOString(),
    blockersCount: 0,
    openQuestionsCount: 0,
  },
  {
    id: "demo-flow-6",
    number: "PR-106",
    clientName: "ТОВ Design Craft",
    title: "Комерційні стелажі",
    currentStepKey: "TASKS_DISTRIBUTED",
    status: "READY_FOR_PROCUREMENT_AND_WORKSHOP",
    readinessPercent: 100,
    riskScore: 21,
    dueDate: new Date(now + 12 * 24 * 60 * 60 * 1000).toISOString(),
    blockersCount: 0,
    openQuestionsCount: 0,
  },
];

export function getDemoCommandCenterView(): ProductionCommandCenterView {
  return {
    kpis: {
      activeFlows: 6,
      blockedFlows: 1,
      averageReadiness: 54,
      highRiskFlows: 1,
      overdueFlows: 1,
      readyToDistribute: 1,
      procurementPending: 3,
      procurementOverdue: 1,
    },
    workshopBottleneck: {
      stageKey: "CUTTING",
      stageLabel: "Порізка",
      taskCount: 2,
      totalWorkshopTasks: 6,
      sharePercent: 33,
    },
    recentEvents: [
      {
        id: "demo-ev-1",
        flowId: "demo-flow-4",
        flowNumber: "PR-104",
        actorName: "Система валідації",
        title: "Пакет файлів не пройшов перевірку",
        description: "Відсутня специфікація фурнітури в пакеті v2.",
        createdAt: new Date(now - 45 * 60 * 1000).toISOString(),
      },
      {
        id: "demo-ev-2",
        flowId: "demo-flow-6",
        flowNumber: "PR-106",
        actorName: "Начальник виробництва",
        title: "Задачі розподілено по цеху",
        description: null,
        createdAt: new Date(now - 3 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "demo-ev-3",
        flowId: "demo-flow-2",
        flowNumber: "PR-102",
        actorName: "Конструктор",
        title: "Призначено конструктора на проєкт",
        description: null,
        createdAt: new Date(now - 26 * 60 * 60 * 1000).toISOString(),
      },
    ],
    queue: DEMO_QUEUE,
    stationLoads: [
      { stationKey: "cutting", stationLabel: "Розкрій", loadPercent: 79 },
      { stationKey: "edging", stationLabel: "Кромка", loadPercent: 65 },
      { stationKey: "drilling", stationLabel: "Свердління", loadPercent: 57 },
      { stationKey: "assembly", stationLabel: "Збірка", loadPercent: 48 },
      { stationKey: "painting", stationLabel: "Фарбування", loadPercent: 36 },
      { stationKey: "packaging", stationLabel: "Пакування", loadPercent: 31 },
    ],
    criticalBlockers: [
      {
        flowId: "demo-flow-4",
        number: "PR-104",
        title: "Столи офісні",
        severity: "CRITICAL",
        message: "Валідація не пройдена: відсутня специфікація фурнітури.",
      },
    ],
    nextActions: [
      {
        flowId: "demo-flow-4",
        number: "PR-104",
        title: "Столи офісні",
        description: "Потік заблоковано. Дозавантажте пакет і повторіть перевірку.",
        ctaLabel: "Відкрити штаб",
      },
      {
        flowId: "demo-flow-2",
        number: "PR-102",
        title: "Шафа-купе",
        description: "Призначено конструктора. Додайте питання у комунікаційний блок.",
        ctaLabel: "Відкрити штаб",
      },
      {
        flowId: "demo-flow-6",
        number: "PR-106",
        title: "Комерційні стелажі",
        description: "Розподіл виконано. Контролюйте канбан цеху та підготуйте монтаж.",
        ctaLabel: "Відкрити штаб",
      },
    ],
    procurement: [
      {
        id: "demo-proc-1",
        flowId: "demo-flow-6",
        flowNumber: "PR-106",
        title: "Сформувати заявку постачальнику плит",
        status: "EXPECTED",
        supplier: "Kronospan UA",
        expectedDate: new Date(now + 3 * 24 * 60 * 60 * 1000).toISOString(),
        receivedDate: null,
      },
      {
        id: "demo-proc-2",
        flowId: "demo-flow-6",
        flowNumber: "PR-106",
        title: "Підтвердити фурнітуру",
        status: "ORDERED",
        supplier: "Blum UA",
        expectedDate: new Date(now + 2 * 24 * 60 * 60 * 1000).toISOString(),
        receivedDate: null,
      },
      {
        id: "demo-proc-3",
        flowId: "demo-flow-5",
        flowNumber: "PR-105",
        title: "Доставка фасадів",
        status: "DELIVERED",
        supplier: "MDF Service",
        expectedDate: new Date(now - 1 * 24 * 60 * 60 * 1000).toISOString(),
        receivedDate: new Date(now - 8 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "demo-proc-4",
        flowId: DEMO_FLOW_ID,
        flowNumber: "PR-101",
        title: "Замовити фурнітуру Blum",
        status: "ORDERED",
        supplier: "Blum UA",
        expectedDate: new Date(now - 2 * 24 * 60 * 60 * 1000).toISOString(),
        receivedDate: null,
      },
    ],
    warehouse: [
      {
        flowId: "demo-flow-5",
        flowNumber: "PR-105",
        material: "MDF фасади білий мат",
        reserved: true,
        incoming: false,
      },
      {
        flowId: "demo-flow-6",
        flowNumber: "PR-106",
        material: "ЛДСП 16mm дуб сонома",
        reserved: false,
        incoming: true,
      },
      {
        flowId: DEMO_FLOW_ID,
        flowNumber: "PR-101",
        material: "ЛДСП Egger 18mm",
        reserved: true,
        incoming: false,
      },
    ],
    workshopKanban: [
      {
        stageKey: "CUTTING",
        stageLabel: "Порізка",
        tasks: [
          {
            id: "demo-workshop-1",
            flowId: "demo-flow-6",
            flowNumber: "PR-106",
            title: "Розкрій панелей секції A",
            priority: "HIGH",
            dueDate: new Date(now + 24 * 60 * 60 * 1000).toISOString(),
            assigneeUserId: null,
            assigneeName: null,
            status: "IN_PROGRESS",
            miniHqLifecycle: {
              state: "RUNNING",
              startedAt: new Date(now - 2 * 60 * 60 * 1000).toISOString(),
              completedAt: null,
              lastResumedAt: new Date(now - 45 * 60 * 1000).toISOString(),
              lastPausedAt: null,
              activeSeconds: 4100,
              pauseReasonCode: null,
              pauseComment: null,
            },
            miniHqProgress: {
              percent: 45,
              source: "manual",
              stageMetricKey: "cuttingMeters",
              stageMetricActual: 9,
              stageMetricPlan: 20,
              lastSyncedAt: new Date(now - 10 * 60 * 1000).toISOString(),
              lastError: null,
            },
            miniHqGitLab: { projectId: null, ref: null, path: null },
            materialsChecklist: [
              { id: "dm1", label: "Специфікація матеріалів на столі", done: true },
              { id: "dm2", label: "Позиції зі складу / резерв", done: false },
            ],
          },
          {
            id: "demo-workshop-2",
            flowId: "demo-flow-5",
            flowNumber: "PR-105",
            title: "Розкрій корпусів",
            priority: "NORMAL",
            dueDate: new Date(now + 48 * 60 * 60 * 1000).toISOString(),
            assigneeUserId: "demo-user-assembler",
            assigneeName: "Олег Збірник",
            status: "TODO",
            miniHqLifecycle: {
              state: "IDLE",
              startedAt: null,
              completedAt: null,
              lastResumedAt: null,
              lastPausedAt: null,
              activeSeconds: 0,
              pauseReasonCode: null,
              pauseComment: null,
            },
            miniHqProgress: {
              percent: 0,
              source: "none",
              stageMetricKey: null,
              stageMetricActual: null,
              stageMetricPlan: null,
              lastSyncedAt: null,
              lastError: null,
            },
            miniHqGitLab: { projectId: null, ref: null, path: null },
            materialsChecklist: [
              { id: "dm3", label: "Специфікація матеріалів на столі", done: false },
              { id: "dm4", label: "Позиції зі складу / резерв", done: false },
            ],
          },
        ],
      },
      {
        stageKey: "EDGING",
        stageLabel: "Поклейка",
        tasks: [
          {
            id: "demo-workshop-3",
            flowId: "demo-flow-6",
            flowNumber: "PR-106",
            title: "Кромкування панелей",
            priority: "HIGH",
            dueDate: new Date(now + 2 * 24 * 60 * 60 * 1000).toISOString(),
            assigneeUserId: null,
            assigneeName: null,
            status: "BLOCKED",
            miniHqLifecycle: {
              state: "PAUSED",
              startedAt: new Date(now - 3 * 60 * 60 * 1000).toISOString(),
              completedAt: null,
              lastResumedAt: null,
              lastPausedAt: new Date(now - 20 * 60 * 1000).toISOString(),
              activeSeconds: 5800,
              pauseReasonCode: "MATERIAL_WAIT",
              pauseComment: "Очікуємо партію кромки",
            },
            miniHqProgress: {
              percent: 31,
              source: "manual",
              stageMetricKey: "edgingMeters",
              stageMetricActual: 6,
              stageMetricPlan: 19,
              lastSyncedAt: new Date(now - 20 * 60 * 1000).toISOString(),
              lastError: null,
            },
            miniHqGitLab: { projectId: null, ref: null, path: null },
            materialsChecklist: [{ id: "dm5", label: "Кромка в рулонах", done: false }],
          },
        ],
      },
      {
        stageKey: "DRILLING",
        stageLabel: "Присадка",
        tasks: [
          {
            id: "demo-workshop-4",
            flowId: "demo-flow-5",
            flowNumber: "PR-105",
            title: "Присадка кріплень",
            priority: "NORMAL",
            dueDate: new Date(now + 2 * 24 * 60 * 60 * 1000).toISOString(),
            assigneeUserId: null,
            assigneeName: null,
            status: "TODO",
            miniHqLifecycle: {
              state: "IDLE",
              startedAt: null,
              completedAt: null,
              lastResumedAt: null,
              lastPausedAt: null,
              activeSeconds: 0,
              pauseReasonCode: null,
              pauseComment: null,
            },
            miniHqProgress: {
              percent: 0,
              source: "none",
              stageMetricKey: null,
              stageMetricActual: null,
              stageMetricPlan: null,
              lastSyncedAt: null,
              lastError: null,
            },
            miniHqGitLab: { projectId: null, ref: null, path: null },
            materialsChecklist: [],
          },
        ],
      },
      {
        stageKey: "ASSEMBLY",
        stageLabel: "Збірка",
        tasks: [
          {
            id: "demo-workshop-5",
            flowId: DEMO_FLOW_ID,
            flowNumber: "PR-101",
            title: "Попередня збірка модулів",
            priority: "HIGH",
            dueDate: new Date(now + 3 * 24 * 60 * 60 * 1000).toISOString(),
            assigneeUserId: "demo-user-assembler",
            assigneeName: "Олег Збірник",
            status: "IN_PROGRESS",
            miniHqLifecycle: {
              state: "RUNNING",
              startedAt: new Date(now - 90 * 60 * 1000).toISOString(),
              completedAt: null,
              lastResumedAt: new Date(now - 25 * 60 * 1000).toISOString(),
              lastPausedAt: null,
              activeSeconds: 3200,
              pauseReasonCode: null,
              pauseComment: null,
            },
            miniHqProgress: {
              percent: 62,
              source: "manual",
              stageMetricKey: "assemblyUnits",
              stageMetricActual: 5,
              stageMetricPlan: 8,
              lastSyncedAt: new Date(now - 5 * 60 * 1000).toISOString(),
              lastError: null,
            },
            miniHqGitLab: { projectId: null, ref: null, path: null },
            materialsChecklist: [
              { id: "dm6", label: "Фурнітура та петлі", done: true },
              { id: "dm7", label: "Кріплення, шурупи, мініфікс", done: true },
              { id: "dm8", label: "Декоративні накладки / ручки", done: false },
              { id: "dm9", label: "Комплектність за специфікацією", done: false },
            ],
          },
        ],
      },
      { stageKey: "PAINTING", stageLabel: "Фарбування", tasks: [] },
      {
        stageKey: "PACKAGING",
        stageLabel: "Пакування",
        tasks: [
          {
            id: "demo-workshop-6",
            flowId: "demo-flow-6",
            flowNumber: "PR-106",
            title: "Пакування до відвантаження",
            priority: "NORMAL",
            dueDate: new Date(now + 4 * 24 * 60 * 60 * 1000).toISOString(),
            assigneeUserId: null,
            assigneeName: null,
            status: "TODO",
            miniHqLifecycle: {
              state: "IDLE",
              startedAt: null,
              completedAt: null,
              lastResumedAt: null,
              lastPausedAt: null,
              activeSeconds: 0,
              pauseReasonCode: null,
              pauseComment: null,
            },
            miniHqProgress: {
              percent: 0,
              source: "none",
              stageMetricKey: null,
              stageMetricActual: null,
              stageMetricPlan: null,
              lastSyncedAt: null,
              lastError: null,
            },
            miniHqGitLab: { projectId: null, ref: null, path: null },
            materialsChecklist: [
              { id: "dm10", label: "Захисна плівка / кутники", done: false },
              { id: "dm11", label: "Маркетинг, етикетки, документи", done: false },
            ],
          },
        ],
      },
    ],
    installation: [
      {
        id: "demo-inst-1",
        flowId: "demo-flow-6",
        flowNumber: "PR-106",
        title: "Монтаж стелажів",
        address: "м. Київ, вул. Велика Васильківська 100",
        date: new Date(now + 6 * 24 * 60 * 60 * 1000).toISOString(),
        team: "Бригада B",
        status: "PLANNED",
      },
      {
        id: "demo-inst-2",
        flowId: "demo-flow-5",
        flowNumber: "PR-105",
        title: "Монтаж кухні",
        address: "м. Київ, вул. Хрещатик 1",
        date: new Date(now + 2 * 24 * 60 * 60 * 1000).toISOString(),
        team: "Бригада A",
        status: "IN_PROGRESS",
      },
    ],
    syncedAt: new Date().toISOString(),
  };
}

export function getDemoOrderHubView(flowId: string): ProductionOrderHubView | null {
  if (!DEMO_FLOW_IDS.includes(flowId as (typeof DEMO_FLOW_IDS)[number])) return null;
  const queue = DEMO_QUEUE.find((item) => item.id === flowId);
  if (!queue) return null;
  const baseStepStates = {
    ACCEPTED_BY_CHIEF: "LOCKED",
    CONSTRUCTOR_ASSIGNED: "LOCKED",
    CONSTRUCTOR_IN_PROGRESS: "LOCKED",
    FILES_PACKAGE_UPLOADED: "LOCKED",
    FILES_VALIDATED: "LOCKED",
    APPROVED_BY_CHIEF: "LOCKED",
    TASKS_DISTRIBUTED: "LOCKED",
  } as const;
  const order = [
    "ACCEPTED_BY_CHIEF",
    "CONSTRUCTOR_ASSIGNED",
    "CONSTRUCTOR_IN_PROGRESS",
    "FILES_PACKAGE_UPLOADED",
    "FILES_VALIDATED",
    "APPROVED_BY_CHIEF",
    "TASKS_DISTRIBUTED",
  ] as const;
  const currentIndex = order.indexOf(queue.currentStepKey);
  const stepStates = order.map((key, idx) => {
    if (idx < currentIndex) return "DONE";
    if (idx === currentIndex) return queue.status === "BLOCKED" ? "BLOCKED" : "IN_PROGRESS";
    if (idx === currentIndex + 1) return "AVAILABLE";
    return baseStepStates[key];
  });

  return {
    flow: {
      id: queue.id,
      number: queue.number,
      title: queue.title,
      clientName: queue.clientName,
      status: queue.status,
      currentStepKey: queue.currentStepKey,
      readinessPercent: queue.readinessPercent,
      riskScore: queue.riskScore,
      dueDate: queue.dueDate,
      chiefName: "Начальник виробництва",
      constructorName: "Studio Draft UA / Внутрішній конструктор",
      constructorMode: "OUTSOURCE",
      constructorWorkspaceUrl: "/constructor/demo-constructor-token",
      telegramThreadUrl: "https://t.me/+enver-production-demo",
    },
    steps: [
      {
        key: "ACCEPTED_BY_CHIEF",
        label: "Прийнято начальником виробництва",
        state: stepStates[0],
        completedAt: stepStates[0] === "DONE" ? new Date(now - 3 * 24 * 60 * 60 * 1000).toISOString() : null,
      },
      {
        key: "CONSTRUCTOR_ASSIGNED",
        label: "Призначено конструктора",
        state: stepStates[1],
        completedAt: stepStates[1] === "DONE" ? new Date(now - 2 * 24 * 60 * 60 * 1000).toISOString() : null,
      },
      {
        key: "CONSTRUCTOR_IN_PROGRESS",
        label: "Конструктор опрацьовує",
        state: stepStates[2],
        completedAt: stepStates[2] === "DONE" ? new Date(now - 24 * 60 * 60 * 1000).toISOString() : null,
      },
      {
        key: "FILES_PACKAGE_UPLOADED",
        label: "Пакет файлів зареєстровано",
        state: stepStates[3],
        completedAt: stepStates[3] === "DONE" ? new Date(now - 20 * 60 * 60 * 1000).toISOString() : null,
      },
      {
        key: "FILES_VALIDATED",
        label: "Пакет перевірено",
        state: stepStates[4],
        completedAt: stepStates[4] === "DONE" ? new Date(now - 12 * 60 * 60 * 1000).toISOString() : null,
      },
      {
        key: "APPROVED_BY_CHIEF",
        label: "Апрув начальником виробництва",
        state: stepStates[5],
        completedAt: stepStates[5] === "DONE" ? new Date(now - 8 * 60 * 60 * 1000).toISOString() : null,
      },
      {
        key: "TASKS_DISTRIBUTED",
        label: "Розподіл у закупівлю та виробництво",
        state: stepStates[6],
        completedAt: stepStates[6] === "DONE" ? new Date(now - 4 * 60 * 60 * 1000).toISOString() : null,
      },
    ],
    blockers:
      queue.blockersCount > 0
        ? [
            {
              id: `demo-blocker-${queue.id}`,
              severity: queue.riskScore >= 70 ? "CRITICAL" : "HIGH",
              title: "Не закрито операційні блокери",
              description: `Активних блокерів: ${queue.blockersCount}.`,
            },
          ]
        : [],
    questions: [
      {
        id: "demo-q-1",
        authorName: "Конструктор",
        source: "INTERNAL",
        text: "Підтвердьте тип фурнітури для верхніх секцій.",
        status: queue.openQuestionsCount > 0 ? "OPEN" : "ANSWERED",
        createdAt: new Date(now - 10 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "demo-q-2",
        authorName: "Конструктор",
        source: "INTERNAL",
        text: "Уточніть колір фасадів (RAL).",
        status: queue.openQuestionsCount > 1 ? "OPEN" : "ANSWERED",
        createdAt: new Date(now - 8 * 60 * 60 * 1000).toISOString(),
      },
    ],
    filePackages: [
      {
        id: "demo-pkg-1",
        packageName: "Пакет конструктива",
        versionLabel: "v1.2",
        fileCount: 6,
        note: "DXF + специфікація + PDF креслення",
        uploadedAt: new Date(now - 18 * 60 * 60 * 1000).toISOString(),
        uploadedByName: "Studio Draft UA",
        validationPassed: currentIndex >= 4,
        approvalStatus: currentIndex >= 5 ? "APPROVED" : "PENDING",
      },
    ],
    tasks: [
      {
        id: "demo-task-1",
        type: "CONSTRUCTOR",
        title: "Доопрацювати креслення фасадів",
        status: currentIndex < 5 ? "IN_PROGRESS" : "DONE",
        assigneeName: "Studio Draft UA",
        dueDate: new Date(now + 2 * 24 * 60 * 60 * 1000).toISOString(),
      },
    ],
    insights: [
      {
        id: "demo-insight-1",
        type: "NEXT_ACTION",
        title: "Рекомендація",
        description:
          queue.openQuestionsCount > 0
            ? `Перед апрувом закрийте ${queue.openQuestionsCount} відкритих питань.`
            : "Критичних питань немає, можна рухати потік далі.",
        severity: queue.openQuestionsCount > 0 ? "MEDIUM" : "LOW",
        recommendedAction:
          queue.openQuestionsCount > 0
            ? "Уточнити технічні питання і повторити перевірку."
            : "Підтвердити поточний крок і перейти до наступного.",
      },
    ],
    timeline: [
      {
        id: "demo-event-1",
        type: "FLOW_ACCEPTED",
        actorName: "Начальник виробництва",
        title: "Потік прийнято в роботу",
        description: null,
        createdAt: new Date(now - 3 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "demo-event-2",
        type: "FILES_PACKAGE_REGISTERED",
        actorName: "Studio Draft UA",
        title: "Зареєстровано пакет файлів",
        description: "Пакет конструктива · v1.2",
        createdAt: new Date(now - 18 * 60 * 60 * 1000).toISOString(),
      },
    ],
  };
}
