import type { CalendarEvent } from "./types";

/** Статичні дати для SSR / уникнення hydration-розбіжностей у демо. */
export const demoCalendarEvents: CalendarEvent[] = [
  {
    id: "1",
    title: "Замір кухні · ЖК RIVER",
    type: "measurement",
    status: "confirmed",
    startAt: "2026-03-20T07:30:00.000Z",
    endAt: "2026-03-20T08:30:00.000Z",
    location: "ЖК RIVER, підʼїзд 3",
    assigneeName: "Марина",
    linkedEntityType: "deal",
    linkedEntityLabel: "Кухня · ЖК RIVER",
    linkedEntityId: "deal_1",
    isCritical: false,
  },
  {
    id: "2",
    title: "Нагадування щодо КП · гардеробна",
    type: "follow_up",
    status: "planned",
    startAt: "2026-03-20T12:00:00.000Z",
    endAt: "2026-03-20T12:30:00.000Z",
    assigneeName: "Антон",
    linkedEntityType: "lead",
    linkedEntityLabel: "Лід · гардеробна котедж",
    linkedEntityId: "lead_1",
    isCritical: true,
    notes:
      "Клієнт очікує оновлений варіант з іншими фасадами.",
  },
  {
    id: "3",
    title: "Монтаж шафи-купе · вул. Сагайдачного",
    type: "installation",
    status: "in_progress",
    startAt: "2026-03-20T09:00:00.000Z",
    endAt: "2026-03-20T14:00:00.000Z",
    location: "вул. Сагайдачного, 12",
    assigneeName: "Монтажна бригада №2",
    linkedEntityType: "order",
    linkedEntityLabel: "Замовлення #5842",
    linkedEntityId: "order_5842",
    isCritical: true,
  },
  {
    id: "5",
    title: "Зустріч з клієнтом · офісні меблі",
    type: "meeting",
    status: "planned",
    startAt: "2026-03-20T15:00:00.000Z",
    endAt: "2026-03-20T16:00:00.000Z",
    assigneeName: "Олег",
    linkedEntityType: "deal",
    linkedEntityLabel: "Офіс · IT компанія",
    linkedEntityId: "deal_2",
    isCritical: false,
  },
  {
    id: "4",
    title: "Виробництво · кухня Loft Studio",
    type: "production",
    status: "planned",
    startAt: "2026-03-21T08:00:00.000Z",
    endAt: "2026-03-21T16:00:00.000Z",
    assigneeName: "Цех · зміна 1",
    linkedEntityType: "order",
    linkedEntityLabel: "Замовлення #5810",
    linkedEntityId: "order_5810",
    isCritical: false,
  },
];
