-- Додаємо окремі ролі для цехових груп і конструктора.
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'CUTTING';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'EDGING';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'DRILLING';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'ASSEMBLY';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'CONSTRUCTOR';
